---
- name: ark | ensure 7zip installed
  kewlfft.aur.aur:
    name: 7zip
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: "-H"
- name: ark | ensure ark installed
  kewlfft.aur.aur:
    name: ark
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: "-H"