---
- name: firefox | ensure firefox installed
  kewlfft.aur.aur:
    name: firefox
    state: present
    use: paru
    extra_args: --mflags --skipinteg
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: firefox | create profile directory
  ansible.builtin.file:
    path: "{{ profile_subdir }}"
    state: directory
    mode: "0755"
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: firefox | symlink config files
  ansible.builtin.file:
    src: "{{ role_path }}/files/firefox/config/{{ item.path }}"
    dest: "{{ profile_dir }}/{{ item.path }}"
    state: link
    force: true
  with_filetree: firefox/config
  when: item.state == "file"
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: firefox | install ff-ultima theme
  ansible.builtin.include_tasks: ff-ultima.yml

- name: firefox | install extensions
  ansible.builtin.include_tasks: install-addon.yml
  vars:
    addon_slug: "{{ item }}"
  loop: "{{ firefox_extensions }}"
  when: firefox_extensions is defined and firefox_extensions | length > 0

- name: firefox | set default search engine
  ansible.builtin.include_tasks: search-engine.yml

- name: firefox | manage bookmarks
  ansible.builtin.include_tasks: bookmarks.yml

- name: firefox | install addons
  ansible.builtin.include_tasks: addons.yml