---
- name: blockbench | ensure blockbench installed
  kewlfft.aur.aur:
    name: blockbench
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: '-H'
  ignore_errors: true
