#!/bin/bash

sudo dnf install -y git ansible python3-dnf

git clone https://github.com/Furglitch/.dotfiles.git -b fedora-swap ~/.dotfiles
cd ~/.dotfiles

if [ ! -d ~/.ansible ]; then
    mkdir ~/.ansible
fi

if [ ! -f ~/.ansible/vault_pass ]; then
    touch ~/.ansible/vault_pass
    chmod 600 ~/.ansible/vault_pass
    read -p "Enter Ansible vault password: " VAULT_PASS
    echo "$VAULT_PASS" > ~/.ansible/vault_pass
else
    VAULT_PASS=$(cat ~/.ansible/vault_pass)
fi

if [ -z "$VAULT_PASS" ]; then
    echo "Vault password cannot be empty. Exiting."
    exit 1
fi

read -sp "Enter sudo password: " SUDO_PASS
if [ -z "$SUDO_PASS" ]; then
    echo "Sudo password cannot be empty. Exiting."
    exit 1
fi

echo

ansible-galaxy collection install -r requirements.yml
ansible-playbook main.yml \
    --vault-password-file ~/.ansible/vault_pass \
    -e "ansible_become_password=${SUDO_PASS}"