---
millennium_themes:
  - name: SpaceTheme
    id: zQndv1rI0FXLh3QTRgOL
    repo: 'https://github.com/SpaceTheme/Steam.git'
    version: main

millennium_plugins:
  - name: hltb-millennium-plugin
    id: f685622bace6
    repo: 'https://github.com/jcdoll/hltb-millennium-plugin.git'
    version: main
  - name: steam-non-steam-playtimes
    id: 02bed50d10a8
    repo: 'https://github.com/k0d13/steam-non-steam-playtimes.git'
    version: main
  - name: steam-size-on-disk
    id: e73371b61eef
    repo: 'https://github.com/k0d13/steam-size-on-disk.git'
    version: main
  - name: SteamHunter-plugin
    id: 13f2dcc363c8
    repo: 'https://github.com/BossSloth/SteamHunter-plugin.git'
    version: main
  - name: steam-librarian
    id: 266c815057f2
    repo: 'https://github.com/luthor112/steam-librarian.git'
    version: main
  - name: steam-collections-plus
    id: a8f305c0bcdb
    repo: 'https://github.com/luthor112/steam-collections-plus.git'
    version: main
