---
vscode_extensions:
  - Catppuccin.catppuccin-vsc-pack
  - edwinhuish.better-comments-next
  - oderwat.indent-rainbow

  - tyriar.sort-lines
  - arthurlobo.easy-codesnap

  - donjayamanne.git-extension-pack
  - vscodevim.vim