---
- name: vscode | ensure vscode installed
  kewlfft.aur.aur:
    name: visual-studio-code-bin
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: vscode | ensure pre-commit installed
  kewlfft.aur.aur:
    name: pre-commit
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: vscode | install extensions
  ansible.builtin.command:
    cmd: "code --install-extension {{ item }}"
  loop: "{{ vscode_extensions }}"
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"
  when: vscode_extensions is defined and vscode_extensions | length > 0

- name: vscode | ensure config directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/Code/User"
    state: directory
    mode: "0755"
  become: true

- name: vscode | symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/code/config"
    dest: "{{ ansible_facts['user_dir'] }}/.config/Code/User"
    state: link
    force: true
  with_filetree: code/config
  when: item.state == "file"
  become: true