---
- name: vscode | ensure vscode installed
  kewlfft.aur.aur:
    name: visual-studio-code-bin
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: '-H'
- name: vscode | ensure pre-commit installed
  kewlfft.aur.aur:
    name: pre-commit
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: '-H'