---
- name: wallpaper | fetch latest upscayl linux metadata
  ansible.builtin.uri:
    url: https://github.com/upscayl/upscayl/releases/latest/download/latest-linux.yml
    method: GET
    return_content: true
  register: upscayl_latest_linux_yml
  changed_when: false

- name: wallpaper | parse latest upscayl filename
  ansible.builtin.set_fact:
    upscayl_latest_filename: >-
      {{
        (
          upscayl_latest_linux_yml.content
          | from_yaml
        ).files
        | default([])
        | selectattr('url', 'defined')
        | map(attribute='url')
        | select('match', '.*\\.rpm$')
        | list
        | first
        | default((upscayl_latest_linux_yml.content | from_yaml).path, true)
      }}
  changed_when: false
