---
- name: millennium | ensure plugins directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.local/share/millennium/plugins"
    state: directory
    mode: "0755"
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: millennium | ensure themes directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.steam/steam/millennium/themes"
    state: directory
    mode: "0755"
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: millennium | install themes
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ role_path }}/files/millennium/repo/themes/{{ item.name }}"
    version: "{{ item.version }}"
    update: yes
    force: true
    accept_hostkey: yes
  loop: "{{ millennium_themes }}"
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: millennium | symlink themes into Steam
  ansible.builtin.file:
    src: "{{ role_path }}/files/millennium/repo/themes"
    dest: "{{ ansible_facts['user_dir'] }}/.steam/steam/millennium/themes"
    state: link
    force: true
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"
  ignore_errors: true

- name: millennium | enable themes
  ansible.builtin.command:
    cmd: "steam steam://millennium/settings/themes/enable/{{ item.id }}"
  loop: "{{ millennium_themes }}"
  ignore_errors: true
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: steam | kill steam
  command: killall steam
  changed_when: false
  ignore_errors: true

- name: millennium | install plugins
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ role_path }}/files/millennium/repo/plugins/{{ item.name }}"
    version: "{{ item.version }}"
    update: yes
    force: true
    accept_hostkey: yes
  loop: "{{ millennium_plugins }}"
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: millennium | symlink plugins into Steam
  ansible.builtin.file:
    src: "{{ role_path }}/files/millennium/repo/plugins"
    dest: "{{ ansible_facts['user_dir'] }}/.local/share/millennium/plugins"
    state: link
    force: true
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"
  ignore_errors: true

- name: millennium | enable plugins
  ansible.builtin.command:
    cmd: "steam steam://millennium/settings/plugins/enable/{{ item.id }}"
  loop: "{{ millennium_plugins }}"
  ignore_errors: true
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: steam | kill steam
  command: killall steam
  changed_when: false
  ignore_errors: true

