---
- name: steam | ensure steam-rom-manager installed
  kewlfft.aur.aur:
    name: steam-rom-manager-bin
    state: present
    use: paru
  become: true
  become_user: "{{ target_user }}"
  become_flags: '-H'
  ignore_errors: true
