---
- name: hyprpaper | ensure hyprpaper installed
  kewlfft.aur.aur:
    name: hyprpaper
    state: present
    use: paru
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: hyprpaper | symlink bin files
  ansible.builtin.file:
    src: "{{ role_path }}/files/hyprpaper/bin/{{ item.path }}"
    dest: "{{ ansible_facts['user_dir'] }}/.local/bin/{{ item.path }}"
    state: link
    force: true
  with_filetree: hyprpaper/bin
  when: item.state == "file"
  notify: hypr | reload hyprland
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: hyprpaper | ensure linux-wallpaperengine installed
  kewlfft.aur.aur:
    name: linux-wallpaperengine-git
    state: present
    use: paru
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: hyprpaper | ensure .local/share/wallpapers directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.local/share/wallpapers"
    state: directory
    mode: "0755"
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: hyprpaper | download wallpapers
  ansible.builtin.include_tasks: wallpaper.yml
