---
- name: hyprpanel | ensure ags-hyprpanel-git installed
  kewlfft.aur.aur:
    name: ags-hyprpanel-git
    state: present
    use: paru
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: hyprpanel | ensure optional dependencies installed
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
    use: paru
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"
  ignore_errors: true
  loop:
    - hyprpicker
    - wf-recorder

- name: hyprpanel | uninstall dunst # hyprpanel has its own notification daemon
  kewlfft.aur.aur:
    name: dunst
    state: absent
    use: paru
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: hyprpanel | ensure .config/hyprpanel directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/hyprpanel"
    state: directory
    mode: "0755"
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: hyprpanel | symlink config files
  ansible.builtin.file:
    src: "{{ role_path }}/files/hyprpanel/config/{{ item.path }}"
    dest: "{{ ansible_facts['user_dir'] }}/.config/hyprpanel/{{ item.path }}"
    state: link
    force: true
  with_filetree: hyprpanel/config
  when: item.state == "file"
  notify: hypr | reload hyprpanel
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: hyprpanel | symlink bin files
  ansible.builtin.file:
    src: "{{ role_path }}/files/hyprpanel/bin/{{ item.path }}"
    dest: "{{ ansible_facts['user_dir'] }}/.local/bin/hyprpanel.{{ item.path }}"
    state: link
    force: true
  with_filetree: hyprpanel/bin
  when: item.state == "file"
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"