---
- name: hyprcursor | ensure hyprcursor installed
  kewlfft.aur.aur:
    name: hyprcursor
    state: present
    use: paru
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: hyprcursor | ensure catppuccin-cursors-mocha installed
  kewlfft.aur.aur:
    name: catppuccin-cursors-mocha
    state: present
    use: paru
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"
