---
- name: hyprpolkitagent | uninstall polkit-kde-agent
  kewlfft.aur.aur:
    name: polkit-kde-agent
    state: absent
    use: paru
  become: true
  become_user: "{{ target_user }}"
  become_flags: '-H'

- name: hyprpolkitagent | ensure hyprpolkitagent installed
  kewlfft.aur.aur:
    name: hyprpolkitagent
    state: present
    use: paru
  become: true
  become_user: "{{ target_user }}"
  become_flags: '-H'
