- name: e621 | load set id
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/wallpapers.yml"
    name: e621_vaulted
  no_log: true

- name: e621 | ensure set id defined
  ansible.builtin.assert:
    that: 
      - e621_vaulted.e621_set is defined
      - e621_vaulted.e621_set | length > 0
    fail_msg: "e621_set variable is not defined in wallpapers.yml"

- name: e621 | query posts for set
  ansible.builtin.uri:
    url: "https://e621.net/posts.json?tags=set:{{ e621_vaulted.e621_set }}&limit=100"
    method: GET
    return_content: yes
    headers:
      User-Agent: "archdot/ansible"
  register: e621_posts
  no_log: false

- name: e621 | collect image URLs
  ansible.builtin.set_fact:
    e621_urls: "{{ e621_posts.json.posts | map(attribute='file.url') | list }}"

- name: e621 | keep full posts list
  ansible.builtin.set_fact:
    e621_posts_list: "{{ e621_posts.json.posts }}"

- name: e621 | artist blacklist
  ansible.builtin.set_fact:
    e621_artist_blacklist:
      - conditional_dnp
      - unknown_artist
      - third-party_edit
      - sound_warning
      - anonymous_artist

- name: e621 | download images
  ansible.builtin.get_url:
    url: "{{ item.file.url }}"
    dest: >-
      {{ ansible_facts['user_dir'] }}/.local/share/wallpapers/
      e6.{{ item.id }}.{{((item.tags.artist | default([]) | reject('in', e621_artist_blacklist) | map('regex_replace','[^A-Za-z0-9_-]+','') | list) | length > 0) | ternary( (item.tags.artist | default([]) | reject('in', e621_artist_blacklist) | map('regex_replace','[^A-Za-z0-9_-]+','') | list) | join('_'), 'unknown' ) }}.{{ item.file.ext }}
    mode: '0644'
    force: no
  loop: "{{ e621_posts_list }}"
  when: 
    - e621_posts_list | length > 0
    - item.file.url | length > 0
  ignore_errors: true
  become: true
  become_user: "{{ target_user }}"
  become_flags: '-H'