- name: e926 | load set id
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/wallpapers.yml"
    name: e926_vaulted
  no_log: true

- name: e926 | ensure set id defined
  ansible.builtin.assert:
    that: 
      - e926_vaulted.e926_set is defined
      - e926_vaulted.e926_set | length > 0
    fail_msg: "e926_set variable is not defined in wallpapers.yml"

- name: e926 | query posts for set
  ansible.builtin.uri:
    url: "https://e926.net/posts.json?tags=set:{{ e926_vaulted.e926_set }}&limit=100"
    method: GET
    return_content: yes
    headers:
      User-Agent: "archdot/ansible"
  register: e926_posts
  no_log: false

- name: e926 | collect image URLs
  ansible.builtin.set_fact:
    e926_urls: "{{ e926_posts.json.posts | map(attribute='file.url') | list }}"

- name: e926 | keep full posts list
  ansible.builtin.set_fact:
    e926_posts_list: "{{ e926_posts.json.posts }}"

- name: e926 | artist blacklist
  ansible.builtin.set_fact:
    e926_artist_blacklist:
      - conditional_dnp
      - unknown_artist
      - third-party_edit
      - sound_warning
      - anonymous_artist

- name: e926 | download images
  ansible.builtin.get_url:
    url: "{{ item.file.url }}"
    dest: >-
      {{ ansible_env.HOME }}/.local/share/wallpapers/
      e9.{{ item.id }}.{{((item.tags.artist | default([]) | reject('in', e926_artist_blacklist) | map('regex_replace','[^A-Za-z0-9_-]+','') | list) | length > 0) | ternary( (item.tags.artist | default([]) | reject('in', e926_artist_blacklist) | map('regex_replace','[^A-Za-z0-9_-]+','') | list) | join('_'), 'unknown' ) }}.{{ item.file.ext }}
    mode: '0644'
    force: no
  loop: "{{ e926_posts_list }}"
  when: e926_posts_list | length > 0