---
- name: ssh | ensure openssh installed
  kewlfft.aur.aur:
    name: openssh
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: '-H'
- name: ssh | ensure sshpass installed
  kewlfft.aur.aur:
    name: sshpass
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: '-H'
- name: ssh | ensure sshfs installed
  kewlfft.aur.aur:
    name: sshfs
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: '-H'