---
- name: jdk-temurin | ensure jdk17-temurin installed
  kewlfft.aur.aur:
    name: jdk17-temurin
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: '-H'
- name: jdk-temurin | ensure jdk21-temurin installed
  kewlfft.aur.aur:
    name: jdk21-temurin
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: '-H'