---
- name: vicinae | uninstall wofi
  kewlfft.aur.aur:
    name: wofi
    state: absent
    use: paru
  become_user: "{{ target_user }}"
  become_flags: '-H'
- name: vicinae | ensure vicinae installed
  kewlfft.aur.aur:
    name: vicinae
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: '-H'