---
- name: vicinae | ensure copr repo is enabled
  community.general.copr:
    host: copr.fedorainfracloud.org
    name: quadratech188/vicinae
    state: enabled
  tags:
    - vicinae

- name: vicinae | ensure vicinae is installed
  ansible.builtin.dnf:
    name: vicinae
    state: present
  tags:
    - vicinae

- name: vicinae | ensure .config/vicinae exists
  ansible.builtin.file:
    path: '{{ ansible_facts["user_dir"] }}/.config/vicinae'
    state: directory
    mode: '0755'
    owner: '{{ target_user }}'
    group: '{{ target_user }}'
  tags:
    - vicinae

- name: vicinae | symlink vicinae config directory
  ansible.builtin.file:
    src: "{{ role_path }}/files/vicinae/config"
    dest: "{{ ansible_facts['user_dir'] }}/.config/vicinae"
    state: link
    force: true
  tags:
    - vicinae