---
- name: xdg-utils | ensure xdg-utils installed
  kewlfft.aur.aur:
    name: xdg-utils
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: '-H'
- name: xdg-utils | run desktop-portal tasks
  ansible.builtin.include_tasks: desktop-portal.yml
