---
- name: dolphin | ensure dolphin installed
  kewlfft.aur.aur:
    name: dolphin
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: '-H'

- name: dolphin | symlink config files
  ansible.builtin.file:
    src: "{{ role_path }}/files/dolphin/config/{{ item.path }}"
    dest: "{{ ansible_facts['user_dir'] }}/.config/{{ item.path }}"
    state: link
    force: true
  with_filetree: dolphin/config
  when: item.state == 'file'
  become: true
  become_user: "{{ target_user }}"
  become_flags: '-H'

- name: dolphin | symlink kde files
  ansible.builtin.file:
    src: "{{ role_path }}/files/kde/config/{{ item.path }}"
    dest: "{{ ansible_facts['user_dir'] }}/{{ item.path }}"
    state: link
    force: true
  with_filetree: kde/config
  when: item.state == 'file'
  become: true
  become_user: "{{ target_user }}"
  become_flags: '-H'