---
- name: git | ensure git installed
  kewlfft.aur.aur:
    name: git
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: '-H'
- name: git | ensure github-cli installed
  kewlfft.aur.aur:
    name: github-cli
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: '-H'