---
- name: zsh | symlink .zshrc
  ansible.builtin.file:
    src: "{{ role_path }}/files/zsh/.zshrc"
    dest: "{{ ansible_facts['user_dir'] }}/.zshrc"
    state: link
    force: true

- name: zsh | ensure zsh is default shell
  ansible.builtin.user:
    name: "{{ target_user }}"
    shell: /usr/bin/zsh