---
- name: betterdiscord | ensure betterdiscordctl installed
  kewlfft.aur.aur:
    name: betterdiscordctl
    state: present
    use: paru
  become: true
  become_user: "{{ target_user }}"
  become_flags: '-H'
  ignore_errors: true
