---
- name: discord | ensure rpmfusion repos are installed
  ansible.builtin.dnf:
    name:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  tags:
    - discord

- name: discord | ensure copr repos are enabled
  community.general.copr:
    host: copr.fedorainfracloud.org
    name: "{{ item }}"
    state: enabled
  loop: "{{ discord_copr_repos }}"
  tags:
    - discord

- name: discord | ensure packages are installed
  ansible.builtin.dnf:
    name: "{{ discord_packages }}"
    state: present
  tags:
    - discord

- name: discord | symlink betterdiscordctl upgrade script (to .local/bin)
  ansible.builtin.file:
    src: "{{ role_path }}/files/betterdiscord/bin/betterdiscord-upgrade"
    dest: "{{ ansible_facts['user_dir']/}}/.local/bin/betterdiscord-upgrade"
    state: link
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: "0755"
    force: true
  tags:
    - discord

- name: discord | symlink BetterDiscord config directory
  ansible.builtin.file:
    src: "{{ role_path }}/files/betterdiscord/config"
    dest: "{{ ansible_facts['user_dir'] }}/.config/BetterDiscord"
    state: link
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    force: true
  tags:
    - discord