---
- name: waterfox | clone ff-ultima repository
  ansible.builtin.git:
    repo: "https://github.com/soulhotel/FF-ULTIMA.git"
    dest: "{{ profile_subdir }}/chrome"
    clone: true
    depth: 1
    version: main
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: waterfox | copy ff-ultima user.js to profile
  ansible.builtin.copy:
    src: "{{ profile_subdir }}/chrome/user.js"
    dest: "{{ profile_subdir }}/user.js"
    mode: "0644"
    force: true
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: waterfox | ensure waterfox killed
  ansible.builtin.shell: "pkill -9 -f waterfox"
  ignore_errors: true

- name: waterfox | ensure waterfox restarted
  ansible.builtin.shell: "nohup waterfox > /dev/null 2>&1 &"
  ignore_errors: true

- name: waterfox | wait for 2 seconds
  ansible.builtin.pause:
    seconds: 2

- name: waterfox | remove ff-ultima user.js
  ansible.builtin.file:
    path: "{{ profile_subdir }}/user.js"
    state: absent
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: waterfox | ensure waterfox killed
  ansible.builtin.shell: "pkill -9 -f waterfox"
  ignore_errors: true

- name: waterfox | symlink prefs.js
  ansible.builtin.file:
    src: "{{ role_path }}/files/waterfox/profile/prefs.js"
    dest: "{{ profile_subdir }}/prefs.js"
    state: link
    force: true
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"  