---
- name: waterfox | ensure waterfox installed
  kewlfft.aur.aur:
    name: waterfox-bin
    state: present
    use: paru
    extra_args: --mflags --skipinteg
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: waterfox | create profile directory
  ansible.builtin.file:
    path: "{{ profile_subdir }}"
    state: directory
    mode: "0755"
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: waterfox | symlink bin files
  ansible.builtin.file:
    src: "{{ role_path }}/files/waterfox/config/{{ item.path }}"
    dest: "{{ ansible_facts['user_dir'] }}/.waterfox/{{ item.path }}"
    state: link
    force: true
  with_filetree: waterfox/config
  when: item.state == "file"
  become: true
  become_user: "{{ target_user }}"
  become_flags: "-H"

- name: waterfox | install ff-ultima theme
  ansible.builtin.include_tasks: ff-ultima.yml

- name: waterfox | install extensions
  ansible.builtin.include_tasks: install-addon.yml
  vars:
    addon_slug: "{{ item }}"
  loop: "{{ waterfox_extensions }}"
  when: waterfox_extensions is defined and waterfox_extensions | length > 0

- name: waterfox | set default search engine
  ansible.builtin.include_tasks: search-engine.yml

- name: waterfox | manage bookmarks
  ansible.builtin.include_tasks: bookmarks.yml

- name: waterfox | install addons
  ansible.builtin.include_tasks: addons.yml