---
- name: waterfox | ensure waterfox installed
  kewlfft.aur.aur:
    name: waterfox-bin
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: '-H'

- name: waterfox | install ff-ultima theme
  ansible.builtin.include_tasks: ff-ultima.yml