---
- name: docker-ce | ensure packages are installed
  ansible.builtin.dnf:
    name: "{{ docker_ce_packages }}"
    state: present
  tags:
    - docker-ce

- name: docker | add user to docker group
  ansible.builtin.user:
    name: "{{ target_user }}"
    groups: docker
    append: yes
  become: true