---
- name: prismlauncher | ensure prismlauncher installed
  kewlfft.aur.aur:
    name: prismlauncher
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: '-H'
  ignore_errors: true

- name: prismlauncher | ensure PrismLauncher/catpacks directory exists
  ansible.builtin.file:
    path: '{{ ansible_facts["user_dir"] }}/.local/share/PrismLauncher/catpacks'
    state: directory
    mode: '0755'
    owner: '{{ target_user }}'
    group: '{{ target_user }}'

- name: prismlauncher | symlink catpacks
  ansible.builtin.file:
    src: '{{ playbook_dir }}/files/prismlauncher/catpacks'
    dest: '{{ ansible_facts["user_dir"] }}/.local/share/PrismLauncher/catpacks'
    state: link
    force: true
  with_filetree: prismlauncher/catpacks
  when: item.state == 'file'
  become: true
  become_user: "{{ target_user }}"
  become_flags: '-H'

- name: prismlauncher | ensure PrismLauncher/iconthemes directory exists
  ansible.builtin.file:
    path: '{{ ansible_facts["user_dir"] }}/.local/share/PrismLauncher/iconthemes'
    state: directory
    mode: '0755'
    owner: '{{ target_user }}'
    group: '{{ target_user }}'

- name: prismlauncher | symlink iconthemes
  ansible.builtin.file:
    src: '{{ playbook_dir }}/files/prismlauncher/iconthemes'
    dest: '{{ ansible_facts["user_dir"] }}/.local/share/PrismLauncher/iconthemes'
    state: link
    force: true
  with_filetree: prismlauncher/iconthemes
  when: item.state == 'file'
  become: true
  become_user: "{{ target_user }}"
  become_flags: '-H'

- name: prismlauncher | ensure PrismLauncher/themes directory exists
  ansible.builtin.file:
    path: '{{ ansible_facts["user_dir"] }}/.local/share/PrismLauncher/themes'
    state: directory
    mode: '0755'
    owner: '{{ target_user }}'
    group: '{{ target_user }}'

- name: prismlauncher | clone Catppuccin theme
  ansible.builtin.git:
    repo: 'https://github.com/catppuccin/prismlauncher.git'
    dest: '{{ ansible_facts["user_dir"] }}/.archdot/roles/prismlauncher/files/prismlauncher/themes/catppuccin'
    version: main

- name: prismlauncher | symlink Catppuccin themes
  ansible.builtin.file:
    src: '{{ playbook_dir }}/roles/prismlauncher/files/prismlauncher/themes/catppuccin/themes'
    dest: '{{ ansible_facts["user_dir"] }}/.local/share/PrismLauncher/themes/'
    state: link
    force: true
  with_filetree: prismlauncher/themes/catppuccin/themes
  become: true
  become_user: "{{ target_user }}"
  become_flags: '-H'