---
- name: plymouth | ensure plymouth installed
  kewlfft.aur.aur:
    name: plymouth
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: '-H'

- name: plymouth | symlink plymouth themes
  ansible.builtin.file:
    src: "{{ role_path }}/files/plymouth/themes/{{ item.path }}"
    dest: "/usr/share/plymouth/themes/{{ item.path }}"
    state: link
    force: true
  with_filetree: plymouth/themes
  when: item.state == 'file'
  become: true

- name: plymouth | set default plymouth theme
  ansible.builtin.command: "plymouth-set-default-theme -R sweet-arch-modified"
  become: true

- name: plymouth | add plymouth to HOOKS in /etc/mkinitcpio.conf
  ansible.builtin.lineinfile:
    file: /etc/mkinitcpio.conf
    regexp: '^HOOKS='
    line: "{{ item }}"
  with_items:
    - "{{ ansible_facts['mkinitcpio_hooks'] | regex_replace('^HOOKS=(.*)\\)', 'HOOKS=\\1 plymouth)') }}"
  become: true

- name: plymouth | add quiet and splash to GRUB_CMDLINE_LINUX_DEFAULT in /etc/default/grub
  ansible.builtin.lineinfile:
    file: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: "{{ item }}"
  with_items:
    - "{{ ansible_facts['grub_cmdline_linux_default'] | regex_replace('^GRUB_CMDLINE_LINUX_DEFAULT=(.*)\\)', 'GRUB_CMDLINE_LINUX_DEFAULT=\\1 quiet splash)') }}"
  become: true

- name: plymouth | update initramfs
  ansible.builtin.command: "mkinitcpio -P"
  become: true