---
- name: gimp | ensure gimp installed
  kewlfft.aur.aur:
    name: gimp
    state: present
    use: paru
  become_user: "{{ target_user }}"
  become_flags: '-H'
  ignore_errors: true

- name: gimp | ensure /usr/share/GIMP/3.2/themes directory exists
  ansible.builtin.file:
    path: '/usr/share/GIMP/3.2/themes'
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: gimp | symlink theme files
  ansible.builtin.file:
    src: "{{ role_path }}/files/gimp/themes/"
    dest: "/usr/share/GIMP/3.2/themes"
    state: link
    force: true
  become: true
  become_flags: '-H'

- name: gimp | ensure config directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/GIMP/3.2"
    state: directory
    mode: '0755'

- name: gimp | symlink config files
  ansible.builtin.file:
    src: "{{ role_path }}/files/gimp/config/{{ item.path }}"
    dest: "{{ ansible_facts['user_dir'] }}/.config/GIMP/3.2/{{ item.path }}"
    state: link
    force: true
  with_filetree: gimp/config
  when: item.state == 'file'
  become: true
  become_flags: '-H'