---
# profile configuration
profile: "default-release"
profile_dir: "{{ ansible_facts['user_dir'] }}/.waterfox"
profile_subdir: "{{ profile_dir }}/qc2khrbb.{{ profile}}"

# List of Firefox extensions to install
waterfox_extensions:
  - ublock-origin
  - bitwarden-password-manager
  - styl-us
  - firefox-color
  - sponsorblock
  - dearrow
  - violentmonkey

firefox_color: "https://color.firefox.com/?theme=XQAAAAJCBAAAAAAAAABBqYhm849SCicxcUcPX38oKRicm6da8pFtMcajvXaAE3RJ0F_F447xQs-L1kFlGgDKq4IIvWciiy4upusW7OvXIRinrLrwLvjXB37kvhN5ElayHo02fx3o8RrDShIhRpNiQMOdww5V2sCMLAfehho7r-tNa1SUtGS7I1CTZPy-PytvuYpnFiOqD91PyT5-oYf07MFNkQL1-mpkSfsafhS81iVCbahFQLTHZeroonPBnAGkaLJ2dRDLmW_ekCLmoty20NcEekV8xFQYv721-QIo9PeuYe33F-mNR9-0e-QMdtuksaYkOl_aH_NyI8RDM1HUiQCcd3StPLq3UyDaJhC_rhvlZWMMwDAuoHMI1RAnUbn3_KGbvErQEyBxxtEkWzHTed2xIpT8jcV1yQY9odOLm0ydbWlYpb-kUOoX_nF9hQq7Gf0ORYtSpGO_uA458GGCpImunZ68j-GfRy90T73zU1VU-sqA_YzfFoSZcZqLLa4UF-FMpwPQeeJR5w4GSti1briOisS9yTOAmYWfRpSbogOZzhEW2o-i8Fje__nq5cE"

userscripts:
  - "https://github.com/re621/re621.Legacy/releases/latest/download/script.user.js"
  - "https://gist.github.com/Furglitch/a63a1dd249f7126b473bd6f1fd76285d/raw/noVNCCopyPasteProxmox.user.js"
  - "https://update.greasyfork.org/scripts/560618/YouTube%20Improvements%20%E2%80%93%20Layout%20%20Video%20Enhancer.user.js"
  - "https://update.greasyfork.org/scripts/508784/YouTube%20HD%20Plus.user.js"
  - "https://update.greasyfork.org/scripts/537017/YouTube%20%2B.user.js"

# Default search engine
default_search_engine: "Kagi Search"
kagi_session_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30376664306239363430326638616530346132646366373565336233633134303237323664333837
          3566623061656131376362353430646130346661656462330a616238643131313731643731663464
          65363934343762363239643065353830613331316433656139336633663065383536633662383533
          3335363836346365320a313661323861616264653164626261623636623065343661323133386531
          37306666643064653563323430396561353661376462363165313463333432366339383237646339
          38303330316339383031323465663933316664323630313638373738323731633337613762353862
          35316635313433333066326439343838316132386563653731376535336265333337396539373866
          61323033666336633235656663333531666266343032643839373338363962393637353535323339
          3163
kagi_search_url: "https://kagi.com/search?token={{ kagi_session_token }}&q={searchTerms}"

# Bookmarks to add to the toolbar
waterfox_bookmarks:
  - name: "YouTube"
    url: "https://www.youtube.com/subscriptions/"
    tags: ""
    keyword: "yt"
  - name: "GitHub"
    url: "https://www.github.com/Furglitch/"
    tags: ""
    keyword: "gh"
  - name: "Furglitch Wiki"
    url: "https://wiki.furglitch.com/"
    tags: ""
    keyword: "wiki"
  - name: "Proton Mail"
    url: "https://mail.proton.me/u/0/inbox"
    tags: ""
    keyword: "pm"
  - name: "Listful"
    url: "https://www.listful.com/furglitch"
    tags: ""
    keyword: "lf"
  - name: "ToyHouse"
    url: "https://toyhou.se/furglitch"
    tags: ""
    keyword: "th"
  - name: "Kitsunet"
    url: "https://www.kitsunet.net/"
    tags: ""
    keyword: "kit"
  - name: "e621"
    url: "https://www.e621.net/posts/"
    tags: ""
    keyword: "e6"