---
- name: fonts | ensure NerdFonts installed
  kewlfft.aur.aur:
    name: nerd-fonts
    state: present
    use: paru
  become_user: aur_builder

- name: fonts | ensure Google Fonts installed
  kewlfft.aur.aur:
    name: ttf-google-fonts-git
    state: present
    use: paru
  become_user: aur_builder